# Generated by Django 5.2.4 on 2025-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="correct_invite_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Подтвержденный инвайт-код",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Инвайт-код"
            ),
        ),
    ]
